name: Linters

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run formatter check with Black
        run: uv run black --check .

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Type check with mypy
        run: uv run mypy src
