name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "uv"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: uv pip install -e ".[dev]"

      - name: Run tests with pytest
        run: uv run pytest
